name: 'Build Ionic React Router'
description: 'Build Ionic React Router'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Install Dependencies
      run: npm install --legacy-peer-deps
      shell: bash
      working-directory: ./packages/react-router

    - uses: ./.github/workflows/download-archive
      with:
        name: ionic-core
        path: ./core
        filename: CoreBuild.zip
    - name: Link Core
      run: npm link && cd ../packages/react-router && npm link @ionic/core
      working-directory: ./core

    - uses: ./.github/workflows/download-archive
      with:
        name: ionic-react
        path: ./packages/react
        filename: ReactBuild.zip
    - name: Link React
      run: npm link && cd ../react-router && npm link @ionic/react
      working-directory: ./packages/react
    - name: Build
      run: npm run build
      shell: bash
      working-directory: ./packages/react-router
    - uses: ./.github/workflows/upload-archive
      with:
        name: ionic-react-router
        output: packages/react-router/ReactRouterBuild.zip
        paths: packages/react-router/dist
