name: 'Build Ionic Vue Router'
description: 'Builds Ionic Vue Router'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Cache Vue Node Modules
      uses: actions/cache@v2
      env:
        cache-name: vue-node-modules
      with:
        path: ./packages/vue/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./packages/vue/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - uses: ./.github/workflows/download-archive
      with:
        name: ionic-vue
        path: ./packages/vue
        input: VueBuild.zip
    - name: Install Vue Router Dependencies
      run: npm install
      shell: bash
      working-directory: ./packages/vue-router
    - name: Sync
      run: npm run sync
      shell: bash
      working-directory: ./packages/vue-router
    - name: Lint
      run: npm run lint
      shell: bash
      working-directory: ./packages/vue-router
    - name: Build
      run: npm run build
      shell: bash
      working-directory: ./packages/vue-router
    - uses: ./.github/workflows/upload-archive
      with:
        name: ionic-vue-router
        output: ./packages/vue-router/VueRouterBuild.zip
        paths: packages/vue-router/dist
