name: 'Ionic Framework Archive Upload'
description: 'Compresses and uploads an archive to be reused across jobs'
inputs:
  paths:
    description: 'Paths to files or directories to archive'
  output:
    description: 'Output file name'
  name:
    description: 'Archive name'
runs:
  using: 'composite'
  steps:
    - name: Create Build Archive
      uses: edgarrc/action-7z@v1
      with:
        args: 7z a -tzip ${{ inputs.output }} ${{ inputs.paths }}
    - name: Upload Build Archive
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.paths }}
