name: 'Ionic Framework Archive Download'
description: 'Downloads and decompresses an archive from a previous job'
inputs:
  path:
    description: 'Input archive name'
  input:
    description: 'Input file name'
  name:
    description: 'Archive name'
runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
    - name: run ls
      run: ls
      shell: bash
    - name: Exract Archive
      run: unzip -o ${{ inputs.input }}
      shell: bash
