name: 'Ionic Framework Archive Download'
description: 'Downloads and decompresses an archive from a previous job'
inputs:
  path:
    description: 'Input archive name'
  name:
    description: 'Archive name'
runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v2
    with:
      name: ${{ inputs.name }}
      path: ${{ inputs.path }}
    - uses: edgarrc/action-7z@v1
      with:
        args: 7z x ${{ inputs.path }} -aoa
