name: 'Build Ionic Vue'
description: 'Build Ionic Vue'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Cache Core Node Modules
      uses: actions/cache@v2
      env:
        cache-name: core-node-modules
      with:
        path: ./core/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./core/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Cache Vue Node Modules
      uses: actions/cache@v2
      env:
        cache-name: vue-node-modules
      with:
        path: ./packages/vue/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./packages/vue/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - uses: ./.github/workflows/download-archive
      with:
        name: ionic-core
        path: ./core
        filename: CoreBuild.zip
    - name: Install Vue Dependencies
      run: npm install
      shell: bash
      working-directory: ./packages/vue
    - name: Link @ionic/core
      run: npm link
      shell: bash
      working-directory: ./core
    - name: Link @ionic/core in @ionic/vue
      run: npm link @ionic/core
      shell: bash
      working-directory: ./packages/vue
    - name: Build
      run: npm run build
      shell: bash
      working-directory: ./packages/vue
    - uses: ./.github/workflows/upload-archive
      with:
        name: ionic-vue
        output: packages/vue/VueBuild.zip
        paths: packages/vue/dist packages/vue/css
