name: 'Test Angular Lint'
description: 'Test Angular Lint'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Cache Angular Node Modules
      uses: actions/cache@v2
      env:
        cache-name: angular-node-modules
      with:
        path: ./angular/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./angular/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Lint
      run: npm run lint
      shell: bash
      working-directory: ./angular
