name: 'Ionic Framework'

on:
  pull_request:
    branches: [ '**' ]

jobs:

  build-vue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/packages/vue
